### ISSUE TITLE
Include MySql

### ISSUE THREAD

**Issue by vchigne** [meteor-stream/meteor-postgres#130]
AFAIK, a possible future MySql Version is not so hard to achieve. Great. BTW, there is the numtel's take on it
https://github.com/numtel/meteor-mysql
Your trigger based implementation of observation is different and numtel's requiere some work on the server configuration and table dependences.

**Comment by Eddolan** [comment]
Thanks for your feedback. Right now the project is still a prototype and is changing pretty quickly so we are focused on implementing just Postgres for now. We are trying to have a stable release by 4/26/2015. After that we will take a look at MySql if there is community interest. 

We took a look at Numtel's code and actually integrated some of it into our implementation of SQL.Collection.

**Comment by wuxianliang** [comment]
Great! I follow Numtel's codes line by line to code a demo of integration  between Meteor and OrientDB. As a demo it works. But the quality is low. So I do suggest after stable release of this project, at least in documents, to point out how to integrate other SQL databases. If we can query tables, trees, and graphs as we need, that would be great! 
If you would like to integrate other databases, please take a look at OrientDB, it is a document-graph database with SQL query language. I think it is a great supplementary of PostgreSQL. Thank you!

https://github.com/wuxianliang/meteor-orientdb-demo

**Comment by vchigne** [comment]
@wuxianliang Thanks for the OrientDB heads up, it seems like a pretty fit for a project I'm working on right now.

**Comment by vchigne** [comment]
@Eddolan Right,is a good practice to develop for one platform first, but reading your code I see that it would be a lot easier to adapt it to Mysql than adapt Numtel's to Postgres. And,  for any practical development purpose MySql and PostgreSql is the same.

**Comment by Eddolan** [comment]
@vchigne When we started the project we picked Postgres for several reasons. The most major of them was Postgres' Notify capabilities which is something that doesn't exist in native MySql AFAIK. Yes there are 3rd party implementations of this including Numtel's liveMySQL npm package, but we felt that these implementations were less efficient than the native Postgres implementation. Our package is heavily reliant on Postgres' notify. 

Another reason we chose Postgres was that it seems to be the community favorite on Meteor's Trello roadmap (which I can see you are familiar with).

**Comment by vchigne** [comment]
I´ve been told that the official Meteor SQL implementation will be either DB agnostic or MySql, but, since there is no date for that I would rather change my development plans to use PostgreSql than work with Mongo. I haven't  noticed what you just told me, I misread the code. Thanks for the clarification.

**Comment by Eddolan** [comment]
Thanks for that great information. Im not surprised that Meteor's official support with be for MySQL because it is able to run on both the client and server, and I would be surprised if the core Meteor team relied on something like alasql. 

I hope that when we get our first stable version out it suits your needs well.

**Comment by vchigne** [comment]
If it scales sure it will.Great project you choose. It could be what meteor needs to be on pair of node itself.
