### ISSUE TITLE
How Are Updates Synced? (Existing pub/sub system for SQL DBs?)

### ISSUE THREAD

**Issue by DaEckster** [meteor-stream/meteor-postgres#216]
Really more of a question than anything, didn't know if there was a place to ask this, but is an efficient sub/pub method similar to MongoDB's oplog being implemented or even available to possibly implement in Postgres or any other RMDB?

**Comment by pdiniz13** [comment]
The sub/pub method currently being used in PostgreSQL's NOTIFY functionality.  We currently don't have something equivalent on the from end yet.
