### ISSUE TITLE
Error: connection Error

### ISSUE THREAD

**Issue by canadaduane** [meteor-stream/meteor-postgres#235]
I can't seem to get through step 1, connecting to the database. When I run the following code:

```javascript
console.log("POSTGRES", process.env.POSTGRES);
books = new SQL.Collection('books');
```

I see:

```
I20150425-12:11:55.362(-6)? POSTGRES postgres://duane@localhost/quarto
W20150425-12:11:55.363(-6)? (STDERR) 
W20150425-12:11:55.363(-6)? (STDERR) /Users/duane/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150425-12:11:55.363(-6)? (STDERR) 						throw(ex);
W20150425-12:11:55.364(-6)? (STDERR) 						      ^
W20150425-12:11:55.375(-6)? (STDERR) Error: connection Error
W20150425-12:11:55.376(-6)? (STDERR)     at Array.SQL.Collection (packages/meteorsteam:meteor-postgres/collection/collection.js:34:1)
W20150425-12:11:55.376(-6)? (STDERR)     at app/quarto.js:29:9
W20150425-12:11:55.376(-6)? (STDERR)     at app/quarto.js:77:3
W20150425-12:11:55.376(-6)? (STDERR)     at /Users/duane/Dropbox/Projects/wordtree/quarto/.meteor/local/build/programs/server/boot.js:222:10
W20150425-12:11:55.376(-6)? (STDERR)     at Array.forEach (native)
W20150425-12:11:55.376(-6)? (STDERR)     at Function._.each._.forEach (/Users/duane/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150425-12:11:55.376(-6)? (STDERR)     at /Users/duane/Dropbox/Projects/wordtree/quarto/.meteor/local/build/programs/server/boot.js:117:5
```

It seems like I'm not using the right username, password, or host; however, if I run psql on the command line, all is well:

```
$ psql -U duane -h localhost quarto
psql (9.4.1)
Type "help" for help.

quarto=# \d
          List of relations
 Schema |    Name    | Type  | Owner 
--------+------------+-------+-------
 public | test_table | table | duane
(1 row)
```

So I thought maybe node-postgres is doing something weird. I created the following script based on its README example:

```javascript
var pg = require('pg');
var conString = "postgres://duane@localhost/quarto";

//this starts initializes a connection pool
//it will keep idle connections open for a (configurable) 30 seconds
//and set a limit of 20 (also configurable)
pg.connect(conString, function(err, client, done) {
  if(err) {
    return console.error('error fetching client from pool', err);
  }
  client.query('SELECT $1::int AS number', ['1'], function(err, result) {
    //call `done()` to release the client back to the pool
    done();

    if(err) {
      return console.error('error running query', err);
    }
    console.log(result.rows[0].number);
    //output: 1
  });
});
```

and it successfully connects:

```
$ node test-pg.js 
1
^C
```

Changing any part of the connection string leads to failure, so I'm confident it is truly successful in its connecting.

Why is `meteor-postgres` failing to connect?

**Comment by pdiniz13** [comment]
Duane can you please post the rest of your code for me to take a look at it? This error is not coming from your Postgres connection but from miniSQL. Are you creating your miniSQL table? Are you publishing the rows you want forked to the client?

**Comment by canadaduane** [comment]
I just have one file:

```
console.log("POSTGRES", process.env.POSTGRES);

books = new SQL.Collection('books');
source_type = new SQL.Collection('source_types');

if (Meteor.isServer){
  books.createTable({
    title:          ['$string'],
    author:         ['$string'],
    year:           ['$number'],
    english_score:  ['$float'],
    source_type_id: ['$integer'],
    source_id:      ['$string'],
    byte_count:     ['$number'],
    word_count:     ['$number'],
    created_at:     ['$datetime'],
    updated_at:     ['$datetime'],
  }).save();

  source_type.createTable({
    name:        ['$string'],
    url_pattern: ['$string'],
  }).save()

  source_type.createRelationship('books', '$onetomany').save();

  books.publish('books', function(){
    return books.select(
      'books.id',
      'books.title',
      'books.author',
      'books.year',
      'books.english_score',
      'books.byte_count',
      'books.word_count',
      'books.created_at',
      'books.updated_at')
      .order('created_at DESC')
      .limit(100);
    // ,
    //   'source.name as source_name',
    //   'source.url_pattern as url_pattern')
    //  .join(['INNER JOIN'], ["usernameid"], [["username", "d"]])
    //  .order('createdat DESC')
    //  .limit(100)
  });
}
```

**Comment by pdiniz13** [comment]
Thanks for the updated info. In order for out pub and sub system to work you would have to add a if Meteor.isClient section. 
There you would have to a use a books.createTable with the columns you are passing in through you books.publish statement. Please note that you can't use underscore in your naming of columns since that causes naming conflicts with miniSQL.

**Comment by canadaduane** [comment]
I'm still a little confused by the error--am I incorrect in my understanding that the following code should be run on both server and client?

```
books = new SQL.Collection('books');
```

It seems, based on the documentation, that the above code is for both and that the differentiation occurs here:

```
if (Meteor.isServer){
  books.createTable({
    title:          ['$string'],
    // ...
  })
}
```

```
if (Meteor.isClient) {
  var bookTable = {
    id: ['$id'],
    // ...
  };
  books.createTable(bookTable);
}
```

Regardless of how I write the code for server or client, meteor is still telling me that the original line, `books = new SQL.Collection('books');` is what is raising the "Error: connection Error" exception.

**Comment by pdiniz13** [comment]
We had actually forgotten to republish the newest version of our code. The code you are using actually requires you to add a connection string when you create a new SQL.Collection. We are pushing the new version out now. Please remove the current package and re add it and your connection error will go away. The new version number is 0.1.3. If you are still getting any errors please let us know.

**Comment by Eddolan** [comment]
This was caused by an oversight on our part where updates were made to the code and documentation, but code was not republished to atmosphere. Essentially you were using v0.1.2 with the documentation of v0.1.3. We have republished to atmosphere and will use branching to avoid this issue going forward. The quickest way to update is just to run from a command line:

   meteor update

After that you should no longer have this bug.

**Comment by canadaduane** [comment]
That did the trick. Thanks.
