### ISSUE TITLE
Migrating the Database

### ISSUE THREAD

**Issue by canadaduane** [meteor-stream/meteor-postgres#243]
So when I first started with meteor-postgres, I naively assumed that `createTable` simply created a table. My current understanding is that it does more than that--it creates a table, and a function, and a trigger. 

I'm trying to figure out what strategy to use for migrations of the database schema. My first impression is that meteor-postgres doesn't consider this a normal strategy--i.e. it appears to assume that the entire database schema is known up front, before the app is completed? Or perhaps the strategy is to always wipe out the schema (and data) and start afresh?

**Comment by pdiniz13** [comment]
The is correct our create table function does generate a table function and trigger for that particular table. We currently dont have a function that allows you to add the notify functionality to an existing table, but we are looking to add that in the next few weeks. In the mean time if you would like to add it yourself in can go ahead and add them into your database manually. You can use the code below and replace this.table with the table name that you are trying to use. Please not that the code below is a JS string representation of SQL query so you will have to remove the quotes, plus sign etc.
  "CREATE OR REPLACE FUNCTION notify_trigger_" + this.table + "() RETURNS trigger AS $$" +
  "BEGIN" +
  " IF (TG_OP = 'DELETE') THEN " +
  "PERFORM pg_notify('notify_trigger_" + this.table + "', '[{' || TG_TABLE_NAME || ':' || OLD.id || '}, { operation: " +
  "\"' || TG_OP || '\"}]');" +
  "RETURN old;" +
  "ELSIF (TG_OP = 'INSERT') THEN " +
  "PERFORM pg_notify('notify_trigger_" + this.table + "', '[{' || TG_TABLE_NAME || ':' || NEW.id || '}, { operation: " +
  "\"' || TG_OP || '\"}]');" +
  "RETURN new; " +
  "ELSIF (TG_OP = 'UPDATE') THEN " +
  "PERFORM pg_notify('notify_trigger_" + this.table + "', '[{' || TG_TABLE_NAME || ':' || NEW.id || '}, { operation: " +
  "\"' || TG_OP || '\"}]');" +
  "RETURN new; " +
  "END IF; " +
  "END; " +
  "$$ LANGUAGE plpgsql; " +
  "CREATE TRIGGER watched_table_trigger AFTER INSERT OR DELETE OR UPDATE ON " + this.table +
  " FOR EACH ROW EXECUTE PROCEDURE notify_trigger_" + this.table + "();";
