### ISSUE TITLE
How do reactive subscription work?

### ISSUE THREAD

**Issue by ccorcos** [meteor-stream/meteor-postgres#244]
I'm trying to build a package like this for neo4j. The existing implementation basically uses Mongo to cache the results of a query. Then when a new query comes in that changes the database, they parse the query and find any cached queries in Mongo that depend and rerun those queries. Thus mongo holds all of the results and syncs everything to the client with a Meteor.subscription.

This seems like a bad solution in the end. Mongo will blow up with caches results and I'm sure the query parser that looks for dependancies has its flaws. Anyways, any suggestions on how I could get started with this? Neo4j has a nice npm package I can use...

**Comment by Eddolan** [comment]
The short answer is that Meteor has a database on each client called minimongo, and uses a process called oplog tailing to keep the databases synchronized. We used PostgreSQL's notify function to alert the client to any changes of the server-side database. For a longer answer:

http://eddiedolanblog.azurewebsites.net/meteor-postgresql/

**Comment by ccorcos** [comment]
Hmm intersting. So postgreql is still limited for production right now -- namely that it has auto publish and no securities implemented yet...

So I was thinking about a more simplified pattern. Suppose there was no client-side database and your subscription and query are basically the same thing...

When you query the database, you have a reactive callback function that gives you all the data. Under the hood, there may be some optimizations, but the basic idea is that any changed to that query will call that function again. This way, it won't be such a pain to create a db driver for the client. In the end, I never use allow-deny rules, I always use meteor methods to update the database, and my client-side queries often reflect the publish queries exactly. This, I'm thinking of something like this:

On the server we can do something like this:
```coffee
Db.publish 'topTenPost', ->
  posts = Db.posts.find({}, {sort:{score: 1}, limit:10)
  users = Db.users.find({_id: {$in: {_.pluck(posts, "userId")}}})
  return {posts, users}
```

Then on the client:
```coffee
sub = Db.subscribe 'topTenPosts'
```

This subscription gets the results of the db and keeps them on the client. When changes happen, those changes are pushed to the client. For now, these results can all be held in a reactive var and you can get them with `sub.results.get()`.  Thus you can use the results of this subscription as a reactive data source.

I see this pattern as a nice compromise to get other databases up and running with Meteor without having to put in a ton of work building a client-side database. We get reactivity, and even if we use a reactive var for the whole set of results, a front-end framework like React would optimize the DOM manipulation.

What do you think about this idea? I'm having a problem getting this project started though. Even a simple poll-and-diff implementation. I'm not terribly familiar with how Meteor fibers work on the server and how I can send ddp messages from the server to a specific client based on a client subscription...

**Comment by wuxianliang** [comment]
I think there is another package fits you idea. https://github.com/numtel/meteor-pg
Both have their advantages.

**Comment by ccorcos** [comment]
Hmm. The leaderboard example is interesting...

https://github.com/numtel/meteor-pg-leaderboard/blob/master/leaderboard.js

That package it pretty short too which is nice. But also undocumented -- what is Meteor.connection?

**Comment by Eddolan** [comment]
@ccorcos I think you made some very good points, but @wuxianliang's comment is spot on. There are other Meteor-SQL implementations which do what you are suggesting, essentially having a reactive select statement. 
The downsides to that approach are they you don't get databases everywhere and latency compensation (2 of the core principles of meteor). 
Database everywhere - Using a reactive cursor clients cannot insert into a client side DB as it does not exist. Instead, the programmer must write the logic of sending this data to the server and then interacting with the DB. 
Latency compensation - When interacting with the database the client must wait for a round trip to and from the server to be complete before they are able to see the updated DOM as a result of the new data. 
Our approach, although ambitious, was to implement a solution that accounted for these 2 aspects.

**Comment by ccorcos** [comment]
The problem with database everywhere is that you don't end up using it in production. Its far to complicated to write all the allow/deny rules necessary in a complicated app. In the end, we often end up using Meteor methods anyways. Now that conveniently uses the client side database for latency compensation, but I think this could be handled somewhat manually... If you know what the update should look like, you could insert it into your `sub.results` and wait for the reactive push to correct it...

**Comment by yoonghm** [comment]
I am still new to meteor but i think the "reactive" shall be a process instead of database so that it is free of database implememtation. This should be made known to meteor core team.

**Comment by ccorcos** [comment]
?

**Comment by yoonghm** [comment]
I was using mobile, somehow the text was truncated. Here it is.

In practice, clients do not modify but only view data. I would suggest to use minimongo or the alasql, whichever is easier and better. With this, we will have "simplicity" and "Meteor.subscribe" for most of the cases. 
To make this implementation simple, data shall be classified into "dynamic data" and "static data". Dynamic data can be handled using minimongo. Static data is handled in the 2nd case below.
Clients that need the real-time update should subscribe to a process (call it A) in the database server.
Clients that generate data will have to use DDP to update one or more processes (call it B1, B2, B3, ...) depending on the data type (primitive data types, video, binary, etc.) in the database server. This is to streamline data update process. Processes B1, B2, B3, etc. update the changes to process A directly. If the data is required by a client, process A will update clients directly, instead of waiting for trigger from the database.

If clients need to static data, it should be done strictly using transaction isolation as provided by PostgreSQL. Delay in transaction is acceptable so long as the data is correctly updated to the tables.
