### ISSUE TITLE
Plans for disconnected - local only app

### ISSUE THREAD

**Issue by vchigne** [meteor-stream/meteor-postgres#245]
Hello. Great Work.
I'm developing a remote salesman app, wich will be used basically disconected for days and then synched with the server. What are the plans for disconected and persistent applications? Is there a way to persist data on the client and synch to the server database several days and reboots later? IIRC, ALASQL has local persistence but your docs say that the local data is created at app boot.

**Comment by Eddolan** [comment]
I think this is a very interesting question that it may make sense for us to address in our implementation. Do you know how regular Meteor w/ mongo would handle this situation?

**Comment by TheAncientGoat** [comment]
Regular meteor doesn't have built-in offline database support, other than third party [GroundDB](https://github.com/GroundMeteor/db), which is a lot less advanced compared to AlaSQL. 

I really like the offline/clientside DB ideas adapted by [PouchDB](http://pouchdb.com/) and [Hoodie](http://hood.ie/), doing this with the Meteor infrastructure would be awesome

**Comment by vchigne** [comment]
AlaSQL is now offering direct support for meteor collections and it's offline capabilities are being reworked IIRC. 


     On Monday, May 18, 2015 9:10 AM, Ryan Swart <notifications@github.com> wrote:
   

 Regular meteor doesn't have built-in offline database support, other than third party GroundDB, which is a lot less advanced compared to AlaSQL. I really like the offline/clientside DB ideas adapted by PouchDB and Hoodie, doing this with the Meteor infrastructure would be awesome—
