### ISSUE TITLE
Possible race condition?

### ISSUE THREAD

**Issue by DenisGorbachev** [meteor-stream/meteor-postgres#247]
If a new row is added to the table between initial SELECT and subsequent LISTEN, it won't be picked up, will it?

Maybe it's better to LISTEN first, then SELECT? The race condition will still be present, and it'll be possible to get "Server sent add for existing id" exception on the client, but at least the data won't be lost in limbo.

(https://github.com/meteor-stream/meteor-postgres/blob/master/packages/meteor-postgres/postgres/serversql.js#L580)

**Comment by barbbella** [comment]
Apologies, I just saw this. Let me check it out and I'll get back to you!
