### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by rclai** [meteor-stream/meteor-postgres#251]
Hello,

I was just wondering if you guys are already working on `SQL.Collection.allow/deny` functionality? Or being able to publish while being able to check on `userId`? If you guys haven't already am I able to contribute? If these features were implemented, it would be huge for this package and I'd love to help.

**Comment by barbbella** [comment]
We aren't currently working on this. I'm writing up contribution guidelines this week. We'd love it if you took a look at it. Thanks!

**Comment by Charpeni** [comment]
How's it going?

**Comment by rclai** [comment]
Not sure if this is going to take hold since MDG said they are going to add official support for it.
