### ISSUE TITLE
Publishing joined queries

### ISSUE THREAD

**Issue by rclai** [meteor-stream/meteor-postgres#252]
[Are these lines of comments](https://github.com/meteor-stream/meteor-postgres/blob/master/packages/meteor-postgres/collection/collection.js#L193-L196) referring to the same thing that @numtel wrote about [here](https://github.com/numtel/meteor-pg/wiki/Publishing-Efficient-Joined-Queries).

**Comment by barbbella** [comment]
Tagging @pdiniz13 on this one.
