### ISSUE TITLE
Underscores in column names

### ISSUE THREAD

**Issue by bpartridge** [meteor-stream/meteor-postgres#253]
Hi all!

I'd be very interested in integrating this project into some of my company's backend admin interfaces - we've got a lot running on Meteor/Mongo, but a number of legacy Postgres databases that could use some realtime interfaces as well! So this seems perfect!

One of my biggest concerns is the wording in the documentation that we shouldn't use underscores in column names because of the client side SQL implementation. Is this still true? I'd love to try to hack on it and submit a pull request, but not sure where to begin. We use underscores liberally in our databases, and it seems like a limitation that could be tackled with some better regexes or an improvement to the parser.

Awesome work all!

**Comment by barbbella** [comment]
Hi! You are unable to use underscores because of settings in the backend of miniSQL. The AlaSQL package would need to be adjusted to fix it. I'm writing up contribution guidelines this week if you're interested in looking into it. Thanks!

**Comment by agershun** [comment]
@barbbella Could you provide more information on this problem? 

I just prepared the working example with underscores in names [in jsFiddle](http://jsfiddle.net/4s36sb64/).
