### ISSUE TITLE
Unsupported TEXT data type

### ISSUE THREAD

**Issue by jurajhrib** [meteor-stream/meteor-postgres#254]
Hey guys, first of all, thanks for the effort put into this package, it's great that someone implemented reactive pgsql.

I've been experimenting with your package a little bit and I noticed only few data types are implemented and the TEXT type is missing. I was thinking about using this for my project where users could basically write articles and nested comments and it would have also some social attributes. I would like to ask if you plan implementing the TEXT type (I was going to try myself, but I thought maybe there is some performance or security reason behind that).

**Comment by barbbella** [comment]
Is there a reason that you don't want to use varchar/string?

**Comment by jurajhrib** [comment]
I would like to be able to store longer strings than 255 chars, which string/varchar doesn't allow - it stores longer strings on the client, but the server refuses to perform INSERT on them.

I was alternatively thinking about combining Mongo and Postgres to address this, but I am still not sure how would this work out, so I had to ask about the TEXT type first.

**Comment by barbbella** [comment]
Ok. I'll take a look. Are there any other data types you're interested in while I'm looking at this?

**Comment by jurajhrib** [comment]
Thanks! I think with TEXT, I would have all sufficient types needed for my use-case.

PS: I didn't want to start a new thead since it's not an code issue - the demo app with udpated code is no longer running on address mentioned in older issue thread. And also it would be really helpful to provide a best practice on when/where is the best place for hooking the createTable in application.

**Comment by barbbella** [comment]
Yes, we meant to move it and didn't complete the transition. Thanks for the reminder. I will update the docs, but I would recommend creating the table where you define your collections. Basically, not the client. Thanks for your feedback!

**Comment by Plasmadog** [comment]
I'd also like to use the text type. And while you're at it, it would be good if $datetime mapped to the timestamp type rather than just date (which has no time component, so at the very least it is currently misleading).
