### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by adenot** [meteor-stream/meteor-postgres#256]
Is meteor-postgres compatible with accounts-ui/accounts-github?

I'm trying to implement a login with github but not sure what steps should I follow to make meteor store users in postgres instead of the local mongo.

I'm new to meteor so not sure if this question is pertinent.

**Comment by barbbella** [comment]
This package is not yet compatible with auth, you'll still need Mongo for that. We're hoping that we'll get some help from other members of the open source community!

**Comment by adenot** [comment]
Thanks!

**Comment by TheAncientGoat** [comment]
@barbbella Have you guys been in contact with the MDG re. mainlining this? Waiting for contributors doesn't always work, and you really have something of value here

**Comment by mebibou** [comment]
:+1:
