### ISSUE TITLE
Does ostrio-Neo4jrectivity poll DB for changes outside of meteor?

### ISSUE THREAD

**Issue by JamesReece** [meteor-stream/meteor-postgres#260]
Sorry for newbie question, but I have been playing with this driver for a few days and cannot get past my final(?) hurdle.

So far, I have;

3) Followed the advice to use methods / calls (https://github.com/VeliovGroup/ostrio-Neo4jreactivity).   

2) Found I needed to return data to session variables (https://github.com/VeliovGroup/ostrio-Neo4jreactivity/issues/17) 

3) Implemented the workaround from 2) using ReactiveVar (different data are returned for each instance of my template).

Found I had to convert the object returned to array to use it (https://forums.meteor.com/t/emulating-cursors-with-neo4jreactivitiy/2753)

4) Finally saw my data reflected in my template within the app.  

Sadly, it seems that when I added these data through the neo4j browser cypher tool, I created some relationships with a typo.  So, I fired up the browser tool, confirmed the issue and took corrective action via delete / create statements to get the relationships in the desired state.

The trouble now is that I cannot get the app to reflect the new state of the data - I have re-started both meteor server and neo4j but I guess that does little if the results of the query are cached in mini mongo.  

I found this http://stackoverflow.com/questions/14637302/meteor-server-side-db-insert-delays) - which suggests the mongoDB driver (used to at least) poll the db for updates outside of meteor app.   Does the neo4j-reactive driver do the same?  How do I get the app to refresh the db method call? 

thanks in advance

**Comment by barbbella** [comment]
This repo is no longer maintained since Meteor announced native support.
